#server.address=0.0.0.0
spring.application.name=Backend

sentry.dsn=https://a5b5621e6d14778bc1fb5f0852914146@o4510919425392640.ingest.de.sentry.io/4510919433519184
# Add data like request headers and IP for users,
# see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
sentry.send-default-pii=true

# Explicitly set the port
#server.port=8081

server.port=${PORT:8080}
server.address=0.0.0.0
